# Generated by Django 3.2.6 on 2021-09-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0002_alter_student_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='credit',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='seat',
            field=models.IntegerField(null=True),
        ),
    ]
