# Generated by Django 3.2.7 on 2021-09-11 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0002_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
