# Generated by Django 3.2.6 on 2021-09-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0003_auto_20210916_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='maxSeat',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='maxCredit',
            field=models.IntegerField(null=True),
        ),
    ]
