# Generated by Django 3.2.7 on 2021-09-11 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0003_delete_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=64)),
                ('student_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='reg.student')),
            ],
        ),
    ]
