# Generated by Django 3.2.6 on 2021-09-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0004_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='student_list',
            field=models.IntegerField(),
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.ManyToManyField(to='reg.Course'),
        ),
    ]
