# Generated by Django 3.2.6 on 2021-09-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0005_auto_20210912_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='student_list',
        ),
        migrations.AddField(
            model_name='course',
            name='student_list',
            field=models.ManyToManyField(to='reg.Student'),
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(null=True),
        ),
    ]
