# Generated by Django 3.2.6 on 2021-09-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0006_auto_20210912_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='student_list',
            field=models.ManyToManyField(to='reg.Student'),
        ),
    ]
