# Generated by Django 3.2.6 on 2021-09-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0007_auto_20210913_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='student_list',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='reg.Student'),
        ),
    ]
