# Generated by Django 3.2.7 on 2021-09-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0008_alter_course_student_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='student_list',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='reg.Student'),
        ),
    ]
